#!/bin/bash

# include the functions and colors
. $(dirname "$0")/functions/bash-functions
. $(dirname "$0")/functions/output-factory

for i in $(git diff --name-only --diff-filter=ACM | grep -E '(.php)$')
    do
        echo "$i"
        p=$(git add $i --verbose)
        echo $p
    done

# git add
. $(dirname "$0")/functions/git-add
hasChanges=$?

# exit if the files have changed since the commit
if [[ "$hasChanges" != "0" ]]; then
    exit 1
fi

# run the factory that generates the output
factory
