#!/bin/bash

# include the functions and colors
. $(dirname "$0")/functions/bash-functions
. $(dirname "$0")/functions/eslint
. $(dirname "$0")/functions/php-cs
. $(dirname "$0")/functions/php-lint

makeTitle "GIT"
echo -e "Committing as $(git config user.name)"
echo -e "$(git status)"
echo -e "$(git add .)"

eslint
eslintResult=$?

phplint
phplintResult=$?

phpcs
phpcsResult=$?

num=$((eslintResult + phplintResult + phpcsResult))

makeTitle "RESULTS"

# if the sum of the results doesn't = 0 then something went wrong
if [[ "$num" != "0" ]]; then
  makeError "Errors were found and the commit was rejected."
  exit 1 #reject
else
  makeSuccess "SUCCESS!"
  exit 0 #accept
fi
