#!/bin/bash

# check if stdout is a terminal...
if test -t 1; then

    # see if it supports colors...
    ncolors=$(tput colors)

    if test -n "$ncolors" && test $ncolors -ge 8; then
        bold="$(tput bold)"
        underline="$(tput smul)"
        standout="$(tput smso)"
        normal="$(tput sgr0)"
        black="$(tput setaf 0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        yellow="$(tput setaf 3)"
        blue="$(tput setaf 4)"
        magenta="$(tput setaf 5)"
        cyan="$(tput setaf 6)"
        white="$(tput setaf 7)"
    fi
fi

function makeTitle()
{
    printf '\n%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
    echo -e "${standout} $1 ${normal}\n"
}

function makeHint()
{
    echo -e "\n${magenta} > HINT: $1 ${normal}"
}

function makeError()
{
    echo -e "${red} ---- $1 ---- ${normal} \r\n"
}

function makeSuccess()
{
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
    echo -e "${standout}${green} $1 ${normal} \r\n"
}
