#!/bin/bash

# check if there are changes
function gitAdd() {
    local hasChanges=0
    makeTitle "GIT"
    echo -e "Committing as $(git config user.name)"
    gitStatus="$(git status)"
    echo -e "$gitStatus"
    echo -e "$(git add .)"

    if [[ "$gitStatus" != *"nothing to commit"* ]]; then
        hasChanges=1
    fi
    return $hasChanges
}
